get-sheets-by-family:
  path: /api/sheets
  controller: App\Core\Controller\SheetsController::getSheetByFamilyAction
  methods: [GET]

get-sheets:
  path: /api/sheets/all
  controller: App\Core\Controller\SheetsController::getAllAction
  methods: [GET]

search-sheets:
  path: /api/search
  controller: App\Core\Controller\SheetsController::searchSheetsAction
  methods: [GET]

add-sheeet:
  path: /api/sheets
  controller: App\Core\Controller\SheetsController::addAction
  methods: [POST]

edit-sheet:
  path: /api/sheet/{id}
  controller: App\Core\Controller\SheetsController::editAction
  methods: [PUT]

delete-sheet:
  path: /api/sheet/{id}
  controller: App\Core\Controller\SheetsController::deleteAction
  methods: [DELETE]