App\Core\Entity\Biography:
  type: entity
  table: biography
  repositoryClass: App\Core\Repository\BiographyRepository

  id:
    id:
      type: integer
      generator: { strategy: AUTO}

  fields:
    dateFrom:
      type: datetime
      nullable: false
    dateTo:
      type: datetime
      nullable: true
    whereIs:
      type: string
      length: 255
      nullable: true
    biographyDescription:
      type: string
      length: 1024
      nullable: true
    graveMarker:
      type: string
      length: 255
      nullable: true
    spouseInformation:
      type: string
      length: 255
      nullabe: true
    date_created:
      type: datetime
      nullable: false
    date_updated:
      type: datetime
      nullable: false
    deleted:
      type: boolean
      nullable: false

  manyToOne:
    sheets:
      targetEntity: \App\Core\Entity\Sheets
      name: sheet_id
      referencedColumnName: id