App\Core\Entity\Structure:
  type: entity
  table: structure
  repositoryClass: App\Core\Repository\StructureRepository

  id:
    id:
      type: integer
      generator: { strategy: AUTO}

  fields:
    version:
      type: string
      length: 50
      nullable: false
    fromDate:
      type: datetime
      nullable: false
    toDate:
      type: datetime
      nullable: false
    date_created:
      type: datetime
      nullable: false
    date_updated:
      type: datetime
      nullable: false
    deleted:
      type: boolean
      nullable: false

  manyToOne:
    family:
      targetEntity: \App\Core\Entity\Family
      name: family
      referencedColumnName: id
    subordinate:
      targetEntity: \App\Core\Entity\Sheets
      name: subordinate
      referencedColumnName: id
    superior:
      targetEntity: \App\Core\Entity\Sheets
      name: superior
      referencedColumnName: id
